name: Upstream sync

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Merge changes
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const timeout = (ms) => new Promise(resolve => setTimeout(resolve, ms))

            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Upstream sync",
              head: "Klipper3d:master",
              base: "snapshot",
              maintainer_can_modify: false
            })

            await timeout(3000)

            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number,
              commit_title: "Merge upstream changes",
              merge_method: "merge"
            })

            await timeout(3000)
